apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anchor-webui-data
  namespace: anchor-webui
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: your-storage-class
